version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: altus4-laravel-example
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - vendor:/var/www/html/vendor
      - node_modules:/var/www/html/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      - APP_ENV=local
      - DB_HOST=mysql
      - DB_DATABASE=altus4_example
      - DB_USERNAME=altus4_user
      - DB_PASSWORD=altus4_password
    command: >
      sh -c "composer install --no-dev --optimize-autoloader &&
             npm ci &&
             npm run build &&
             php artisan migrate --force &&
             php artisan db:seed --force &&
             php artisan serve --host=0.0.0.0 --port=8000"

  mysql:
    image: mysql:8.0
    container_name: altus4-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: altus4_example
      MYSQL_USER: altus4_user
      MYSQL_PASSWORD: altus4_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
    driver: local
  vendor:
    driver: local
  node_modules:
    driver: local